### ISSUE TITLE
leetcode.js:638 Uncaught Error: Extension context invalidated.     at leetcode.js:638:28

### ISSUE THREAD

**Issue by javadev** [QasimWani/LeetHub#508]
## Please review previous closed issues before filling out a new one! Duplicate issues will be closed without comment.

**Describe the bug**
There is an error message in console leetcode.js:638 Uncaught Error: Extension context invalidated.     at leetcode.js:638:28

**To Reproduce**
1. Disable the extension
2. Enable extension

**Expected behavior**
No errors

**Screenshots**
![image](https://user-images.githubusercontent.com/348496/223952192-36b7096a-fa87-4399-8912-8f68013d1d39.png)

**Additional context**
I uninstalled and installed extension

**Comment by javadev** [comment]
Workaround - use Firefox and leethub extension
